### ISSUE TITLE
Group names do not uniquely identify a burst

### ISSUE THREAD

**Issue by alexamici** [bopen/xarray-sentinel#12]
Group names do not uniquely identify a burst, it possible (even if unlikely) that two relative orbits will have identical group names for different bursts, e.g. group="IW2/N433_W0120_VV".

@aurghs: "The relative orbit is useful mainly to identify uniquely the bursts, I would rather add the orbit in the burst name, for example:  `group="IW2/N433_W0120_VV_T22"`"

@alexamici: "I agree with the idea, but prefer: `group="IW2/R022_N433_W0120_VV"` (R for "relative orbit" and keep the name to a fixed length).

I also noticed that the polarisations should really be bands of the same dataset, not different datasets, but that is another issue (they have identical dimensions and coordinates)"

_Originally posted by @alexamici in https://github.com/bopen/xarray-sentinel/pull/8#issuecomment-819350889_

**Comment by aurghs** [comment]
> I also noticed that the polarisations should really be bands of the same dataset, not different datasets, but that is another issue (they have identical dimensions and coordinates)"


I think we all agree on putting the bands VV and VH  in the same dataset. 

This identifier for the burst for me would be ok: 
`group="IW2/R022_N433_W0120"`

**Comment by corrado9999** [comment]
This issue should be fixed now, although we still have the problem that, due to the rounding, the same "logical" burst present in two different acquisitions (same relative orbit) could get two different identifiers. We should probably handle this in a separate issue, though.

**Comment by alexamici** [comment]
@corrado9999 I agree, closing.
