### ISSUE TITLE
Add support to open zipped products like other tools do

### ISSUE THREAD

**Issue by alexamici** [bopen/xarray-sentinel#15]

**Comment by alexamici** [comment]
This should probably be solved by using `fsspec` that would enable a host of other features like opening products in the could and chaining protocols.

**Comment by corrado9999** [comment]
It does not look closed to me, the linked pull request contained some refactoring propedeutic to the introduction of `fsspec`, but no actual call to it has been added.

**Comment by alexamici** [comment]
I closed it by mistake while I messed up a partial merge :/

Anyway getting closer to have:

`sentinel1.open_dataset("gs://mybucket/S1B_IW_SLC__1SDV_20210401T052622_20210401T052650_026269_032297_EFA4.SAFE")`

and

`sentinel1.open_dataset("zip://*/manifest.safe::tests/data/S1B_IW_SLC__1SDV_20210401T052622_20210401T052650_026269_032297_EFA4.zip")`

to work.

**Comment by alexamici** [comment]
I'm now at the point that I can open the root dataset with `sentinel1.open_dataset("gs://mybucket/S1A_...SAFE")` and I realised that looking for all the available files and opening the annotation files to get the GCP to compute the burst names over the network is painfully slow :/

We should probably move operations that open files (possibly on the network) to be more explicit,

**Comment by alexamici** [comment]
The issue looks solved since some time. We need to add some documentation, but this is true in general.
