### ISSUE TITLE
Add function to inspect the available data 

### ISSUE THREAD

**Issue by aurghs** [bopen/xarray-sentinel#16]
Would be nice to have a function that inspects the product directory, in order to expose to the user only the groups that are effectively available.

**Comment by corrado9999** [comment]
Is this still valid? We now check whether the annotation file is present and, if not, we remove the corresponding ssubswath.

**Comment by alexamici** [comment]
@corrado9999 yes this is in `main` since some time. @aurghs I close this one as well.
