### ISSUE TITLE
Implement drop_variables key.

### ISSUE THREAD

**Issue by aurghs** [bopen/xarray-sentinel#34]
Currently, the `drop_variabiales` key in open_dataset is ignored.  It should be implemented.

**Comment by alexamici** [comment]
This is low priority as data access is always lazy, so there's no performance penalty in reading all the variables, and the main reason for dropping variables is to avoid crashes due to badly encoded of corrupted data.

**Comment by aurghs** [comment]
yes, but this key is not optional in Xarray backend interface. So we need at least a warning to advise that it is not implemented
