### ISSUE TITLE
Identify bursts groups also using the burst number 

### ISSUE THREAD

**Issue by aurghs** [bopen/xarray-sentinel#36]
Scheme proposed by @alexamici:
- [x] remove the (slow) parsing of GCP on `open_dataset(..., group=None)` and only report available groups by burst_id, e.g. `["IW1/1", "IW1/2", ...]`
- [ ] move the naming logic to an external function in `xarray_sentinel` that takes either the filename or the gcp dataset (whatever is more reasonable) and returns the mapping between the label and the burst_id

**Comment by scottyhq** [comment]
@aurghs @alexamici this is a neat project! I was just starting to get familiar with the structure and am wondering what the current burst_id naming scheme is? I don't think it's obvious from the example in the readme:
```
sentinel1.open_dataset(product_path, group="IW1/R168-N459-E0115")
```
I think a global burst index would be useful for S1 SLC workflows, but I'm not aware of such a thing. For example SAR processing software like [ISCE2](https://github.com/isce-framework/isce2). opens a SLC and uses relative burst numbers (0-9).

**Comment by scottyhq** [comment]
pinging @piyushrpt thinking back to your Sentinel-1 ARD presentation I think the approach was to use a labeling scheme like burstid = {track}-{ascending_node_time}-{swath}-{polarization} ? Would be really great to have a standard label for various software projects to use !

**Comment by alexamici** [comment]
@scottyhq you are right, the burst labelling is based on the internal scheme that we used at @bopen, it has the advantage that interferometric bursts have the same label across satellites, but it has the bigger disadvantage that it is a new convention, not anything used by ESA.

At the moment we are refactoring the labels used throughout the backend to be as close as possible to the original naming scheme.

We plan to provide functions to query the products and transform the datasets in a way that are more useful, but their use will be optional.

**Comment by piyushrpt** [comment]
Pretty much all groups use a ascending node based scheme since you don't need to read a lot of metadata or do geometry based computations to do the labeling. Lot of them are in public literature, e.g - https://www.mdpi.com/2072-4292/12/18/2960/htm . Exact implementation doesnt matter as long as the labeling is consistent.

**Comment by piyushrpt** [comment]
Looks like standard labels are being released - https://forum.step.esa.int/t/sentinel-1-ipf3-4-product-specification-released/30510

**Comment by aurghs** [comment]
That's great news!

**Comment by alexamici** [comment]
@scottyhq & @piyushrpt current `main` is a big refactor and there is a defined way to access burst data via the burst index in the swath.

See: https://github.com/bopen/xarray-sentinel#crop-single-slc-burst-dataset

I plan to make a release soon, then we will try to add more ways to identify and access a burst.

**Comment by alexamici** [comment]
We added the crop-by-burst_id in #100 and I think this is good enough to close this issue as well 🎊
