### ISSUE TITLE
`get_tag_list` can return a dictionary

### ISSUE THREAD

**Issue by corrado9999** [bopen/xarray-sentinel#47]
If the requested tag has one or more attributes, `xmlschema` returns a `dict` with the attribute names as keys plus the key `$` for the actual list.

**Comment by alexamici** [comment]
Did you hit this bug when doing something useful? If not I'd just add and `assert isinstance(tag_list, list)`.

**Comment by alexamici** [comment]
As far as I am concerned https://github.com/bopen/xarray-sentinel/commit/4f2a272e941477b6d67407f116dea5a2e955eeac fixes this bug. @corrado9999 please close it if you agree.

**Comment by corrado9999** [comment]
@alexamici yes, I was trying something useful, but I have just realised I was doing it in the wrong way. Instead of asking for `calibrationVector` I asked for the common parent `calibrationVectorList`. The issue still persist in the degenerated case when e.g. only one `calibrationVector` is present, but it should not arise with our data, the `assert` should be enough.
