### ISSUE TITLE
Parse the XML files via `xmlschema` and the XSD definitions

### ISSUE THREAD

**Issue by alexamici** [bopen/xarray-sentinel#5]
Most metadata are distributed in XML files (e.g. manifest.safe, product/swath and calibration files) and the product zip file contains part of the XSD definition to use.

As the XSD schemas are required when using `xmlschema` we need a way to always have a set of files. Strategy is:
1. allow the user to specify a set of XSD files as a mapping from *namespace* to *path to the schema file*
2. look for the distributed schema files based on a predefined product folder structure e.g. `top_dir/support/s1-level-1-product.xsd`
3. use a mapping from *namespace* to *shipped schema file*

**Comment by alexamici** [comment]
3. is mostly closed by #6. Also #7 is related.

**Comment by aurghs** [comment]
I think #11 close this issus.
