### ISSUE TITLE
CInt16 dtypes cast to complex128

### ISSUE THREAD

**Issue by scottyhq** [bopen/xarray-sentinel#58]
Just wanted to note as I was trying out xarray-sentinel loading bursts (which are CInt16 dtype), they are cast to numpy.complex128. A 2X memory footprint is cumbersome for these already large full-resolution rasters. I realized this is coming from the rasterio library, so I've opened an issue here https://github.com/mapbox/rasterio/issues/2182.

**Comment by alexamici** [comment]
@scottyhq this looks actually fixed in *rasterio*. Thanks a lot!
